from thefuzz import process

def extract_symptoms(text, symptoms):
    text = text.lower()
    words = text.split()
    extracted_symptoms = {}

    for symptom in symptoms:
        symptom = symptom.lower()
        for word in words:
            match = process.extractOne(symptom, [word])
            if match and match[1] > 80:
                extracted_symptoms[symptom] = match[1]
    return extracted_symptoms


# List of symptoms
symptoms = [
    "headache",
    "nausea",
    "fatigue",
    "cough",
    "sore throat",
    "runny nose",
    "fever",
    "rash",
    "itching",
    "skin rash",
    "muscle pain",
    "joint pain",
    "breathing difficulty",
    "chest pain",
    "abdominal pain",
    "vomiting",
    "diarrhea",
    "dizziness",
    "headache",
    "loss of appetite",
    "weight loss",
    "fatigue",
    "swelling",
    "joint pain",
    "muscle pain",
    "skin rash",
    "nodules",
    "skin lesions",
    "skin sores",
    "inflammation",
    "skin redness",
    "skin irritation",
    "skin itching",
    "skin burning",
    "skin peeling",
    "skin cracking",
    "skin flaking",
    "skin scaling",
    "skin shedding",
    "skin crusting",
    "skin hardening",
    "skin thickening",
    "skin tightening",
    "skin dryness",
    "skin roughness",
    "skin redness",
    "skin inflammation",
    "skin irritation",
    "skin itching",
    "skin burning",
    "skin peeling",
    "skin cracking",
    "skin flaking",
    "skin shedding",
    "skin crusting",
    "skin hardening",
    "skin thickening",
    "skin tightening",
    "skin dryness",
    "skin roughness",
    "skin redness",
    "skin inflammation",
    "skin irritation",
    "skin itching",
    "skin burning",
    "skin peeling",
    "skin cracking",
    "skin flaking",
    "skin shedding",
    "skin crusting",
    "skin hardening",
    "skin thickening",
    "skin tightening",
    "skin dryness",
    "skin roughness",
    "skin redness",
    "skin inflammation",
    "skin irritation",
    "skin itching",
    "skin burning",
    "skin peeling",
    "skin cracking",
    "skin flaking",
    "skin shedding",
    "skin crusting",
    "skin hardening",
    "skin thickening",
    "skin tightening",
    "skin dryness",
    "skin roughness",
    "skin redness",
    "skin inflammation",
    "skin irritation",
    "skin itching",
    "skin burning",
    "skin peeling",
    "skin cracking",
    "skin flaking",
    "skin shedding",
    "skin crusting",
    "skin hardening",
    "skin thickening",
    "skin tightening",
    "skin dryness",
    "skin roughness",
    "skin redness",
    "skin inflammation",
    "skin irritation",
    "skin itching",
    "skin burning",
    "skin peeling",
    "skin cracking",
    "skin flaking",
    "skin shedding",
    "skin crusting",
    "skin hardening",
    "skin thickening",
    "skin tightening",
    "skin dryness",
    "skin roughness",
    "skin redness",
    "skin inflammation",
    "skin irritation",
    "skin itching",
    "skin burning",
    "skin peeling",
    "skin cracking",
    "skin flaking",
    "skin shedding",
    "skin crusting",
    "skin hard",
    "skin thickening",
    "skin tightening",
    "skin dryness",
    "skin roughness",
    "skin redness",
    "skin inflammation",
    "skin irritation",
    "skin itching",
    "skin burning",
    "skin peeling",
    "skin cracking",
    "skin flaking",
    "skin shedding",
    "skin crusting",
    "skin hardening",
    "skin thickening",
    "stomach ache",
    "stomach pain",
    "stomach pain",
    "stomach upset",
    "stomach discomfort",
    "stomach cramps",
    "stomach bloating",
]

print(extract_symptoms("I have a stomachache and a strong headache and nausea", symptoms))
